-- Run this once in Supabase: SQL Editor -> New query -> paste -> Run.
-- One small table holds the app's data (settings, leads, messages, funnel counts) as JSON documents.
create table if not exists public.kv (
  key        text primary key,
  value      jsonb       not null,
  version    integer     not null default 1,
  updated_at timestamptz not null default now()
);

-- Lock the table down: no public access at all. Only the app's server (using the secret key) can read or write it.
alter table public.kv enable row level security;
revoke all on public.kv from anon, authenticated;

-- Photo storage: a private bucket for roof photos customers add on the result screen.
-- Private (public = false): nobody can read a photo without a short-lived signed link generated by our server.
-- file_size_limit / allowed_mime_types are enforced by Supabase itself, since photos upload directly from the
-- customer's browser to Supabase (never through our own server - see docs in app/api/photos/sign).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('photos', 'photos', false, 20971520, array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'image/heif'])
on conflict (id) do update set file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
